Fix to handle large png frames
eight04/pyAPNG pull request #12
Opened 2019-02-01 13:52 UTC by bpotard

This PR fixes a bug where individual PNG frames were not valid when saved as individual PNG files. This was traced to a bug in the APNG load code, where the "head_chunks" were added before _each_ data chunk, instead of just once per frame. This only affected "large" PNG files, i.e. frames that didn't fit in a single data chunk.

2019-02-01 17:12 UTC, eight04 commented
We need a test case.

2019-02-02 17:26 UTC, bpotard commented
Sure!
```shell
wget http://littlesvr.ca/apng/images/Contact.png
```

Then in python:
```python
from apng import APNG
from wand.image import Image
im = APNG.open("Contact.png")
for i, (png, control) in enumerate(im.frames):
  png.save("{i}.png".format(i=i))

Image(filename="0.png")
```
You get:
```
wand.exceptions.CoderError: Not enough image data `0.png' @ error/png.c/MagickPNGErrorHandler/1643
```
The file is 65411 bytes.
The file cannot be displayed by firefox and probably some other browsers, chrome displays half of the image; pillow appears fine with it?

With my fix:
0.png is 64618 bytes.
It can be opened by wand, firefox, etc.

Hope that helps!

2019-02-10 12:15 UTC, eight04 requested changes
I have added the disassemble test to the master branch and confirmed it works. Would you like to add the assemble test? You need to extract each frame to the fixture folder:
https://github.com/eight04/pyAPNG/tree/master/test/fixtures/multi_fdat

Here is an example:
https://github.com/eight04/pyAPNG/tree/master/test/fixtures/ball

2019-02-10 12:15 UTC, eight04 commented on apng/__init__.py
> +		new_frame = True
We should rename this flag to `frame_has_head_chunks = False`.

2019-02-10 12:15 UTC, eight04 commented on apng/__init__.py
> +					new_frame = True
This line should be inserted after L467 and changed to `frame_has_head_chunks = False`.

2019-02-10 12:15 UTC, eight04 commented on apng/__init__.py
> +				if new_frame:
`if not frame_has_head_chunks:`, etc.

2019-02-10 18:25 UTC, bpotard commented
All the requested changes have now been done, and it appears the tests are passing fine.

2019-02-10 23:01 UTC, eight04 approved these changes

2019-02-10 23:06 UTC, eight04 commented
:+1: Any idea why we have such messy diffs on Github? It looks fine in the terminal with `git diff master` command.

2019-02-10 23:07 UTC, merged